packages:
  - 'packages/app'
  - 'packages/pipeline'
  - 'packages/fact-extractor'
  - 'packages/fact-analyzer'
  - 'packages/shared'

catalogs:
  react:
    react: '19.2.0'
    react-dom: '19.2.0'

  dev:
    typescript: '5.8.2'
    vite: '6.2.0'
    tailwindcss: '3.4.0'
